language: c
cache: ccache
sudo: true
dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - git
    - curl
    - libelf-dev
    - flex
    - bison
    - autoconf
    - python3-pip

before_install:
  - sudo pip3 install --upgrade pip setuptools
  - sudo pip3 install --ignore-installed six
  - sudo pip3 install fusesoc

install:
  - .travis/install-${JOB}.sh

script:
  - export PIPELINE=MAROCCHINO
  - export EXPECTED_FAILURES=${EF}
  - export EXTRA_CORE_ARGS=${EXTRA}
  - .travis/run-${JOB}.sh

matrix:
  fast_finish: true

jobs:
  include:
    - stage: verilator
      env: JOB=verilator
    - stage: testing
      env: JOB=or1k-tests SIM=icarus EF="or1k-cy or1k-ov or1k-shortjump"

